# Generated by Django 5.2 on 2025-05-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0002_alter_promo_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='image_url',
            field=models.ImageField(default='', upload_to='promotions/', verbose_name='Imagen de la promoción'),
            preserve_default=False,
        ),
    ]
