# Generated by Django 5.2 on 2025-04-29 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del restaurante')),
                ('theme_color', models.CharField(max_length=20, verbose_name='Color del tema')),
                ('font_family', models.CharField(max_length=50, verbose_name='Tipografía')),
                ('background_image_url', models.URLField(blank=True, null=True, verbose_name='Imagen de fondo')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Logo del restaurante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_url', models.URLField(verbose_name='URL del código QR')),
                ('diner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='diners.diner', verbose_name='Restaurante')),
            ],
        ),
    ]
