# Generated by Django 5.2 on 2025-05-03 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diner',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='diner',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='diner',
            name='address',
            field=models.CharField(default='direccion', max_length=255, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='diner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='diner',
            name='theme',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tema de colores'),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='red social')),
                ('url', models.URLField(verbose_name='URL de la pagina')),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_urls', to='diners.diner', verbose_name='Restaurante')),
            ],
        ),
    ]
