# Generated by Django 5.2 on 2025-05-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diners', '0002_remove_diner_font_family_remove_diner_theme_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMedia',
            new_name='SocialMediaURL',
        ),
    ]
