# Generated by Django 5.2 on 2025-05-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diners', '0003_rename_socialmedia_socialmediaurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diner',
            name='background_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_url',
            field=models.ImageField(upload_to='qrcodes/', verbose_name='URL del código QR'),
        ),
    ]
