# Generated by Django 5.2 on 2025-04-29 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='diners.diner', verbose_name='Restaurante')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menus.category', verbose_name='Categoría padre')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del platillo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de imagen del platillo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='menus.category', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la opción')),
                ('extra_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio extra')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menus.meal', verbose_name='Platillo')),
            ],
        ),
    ]
