# Generated by Django 5.2 on 2025-05-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='platillos', verbose_name='URL de imagen del platillo'),
        ),
    ]
