# Generated by Django 5.2 on 2025-05-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_meal_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image_url',
            field=models.ImageField(upload_to='platillos', verbose_name='URL de imagen del platillo'),
        ),
    ]
